### PR TITLE
Integration test

### LINKED ISSUE #24: shovel mechanism does not work with central EGA MQ
### Description

Current configuration does not work with the CEGA Connection as the shovelling does not move messages properly.
We need to repair the shovel configuration.

Ideal this task will add also the tests to see if these still work. one would need:
- fake Central EGA MQ - rabbitmq
- interceptor to work on the Central EGA MQ to process messages

see: https://github.com/EGA-archive/LocalEGA/tree/master/deploy/bootstrap/run for possible configuration

### Definition of Done

Shovel configuration changed

### How to test

Preferably integration tests in github CI

### PR DESCRIPTION
**Pull request by jbygdell**
### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [X] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

Adds an docker-compose based integration test to be run on each PR.
Pipline images are set to `latest` from the GitHub Container repository.
Checks are made at the following point in the ingestion workflow:
* on shoveling to files.inbox
* on shoveling to files.verified
* on shoveling to files.completed
* DB check in the end to ensure the data set ID is correct in the end.

### Changes made:

1. fixed the entrypoint script to create the shovels correctly
2. whitespace and shellsheck fixes to the entrypoint script
3. added an gitignore file so we don't commit test files by misstake
4. added a bunch of helper scripts
5. added the integration test

### Related issues:

Fixes #24

### CODE REVIEW

**Review by blankdots — APPROVED** [review]
looks very good.

**Review by norling — APPROVED** [review]

**Review by a-ghanem — APPROVED** [review]
LGTM

**Review by kjellp — APPROVED** [review]
Looks good to me. I saw some SE specific Cert req (req_distinguished_name Section in setup/ssI.cnf file) that I'm unsure of should be included ?

**Comment by jbygdell** [comment]
> Looks good to me. I saw some SE specific Cert req (req_distinguished_name Section in setup/ssI.cnf file) that I'm unsure of should be included ?

That is not SE specific, it can be needed if the container is running under a different name than the SAN in the certificate.
Like if you run this in docker with public certificates then the public hostname will not match the name in the docker environment.

**Comment by jbygdell** [comment]
> req_distinguished_name

Needs to be there, for the test suit it doesn't matter what the values are really

**Pull request merged**
